version: '3.3'

services:

  # The Spring Cloud Gateway will be the ONLY Docker instance
  # that does open a port accessible from outside the
  # Docker network.

  scg:
    build:
      context: ./scg
      dockerfile: Dockerfile
    ports:
      - "80:8080"
    depends_on:
        - eureka

  eureka:
    build:
      context: ./eureka
      dockerfile: Dockerfile

  ticket_service:
     build:
        context: ./ticket
        dockerfile: Dockerfile
     depends_on:
        - scg

  service_1:
     build:
        context: ./auth
        dockerfile: Dockerfile
     depends_on:
        - scg