spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
      - id: auth-service
        uri: lb://auth-service
        predicates:
        - Path=/auth/**
        filters:
        - RewritePath=/auth/(?<path>.*), /$\{path}
      - id: ticket-producer
        uri: lb://ticket-service
        predicates:
        - Path=/ticket/**
        filters:
        - RewritePath=/ticket/(?<path>.*), /$\{path}
      - id: movie-producer
        uri: lb://movie-service
        predicates:
        - Path=/movie/**
        filters:
        - RewritePath=/movie/(?<path>.*), /$\{path}

eureka:
  instance:
    preferIpAddress: true
  client:
    serviceUrl:
      defaultZone: http://eureka:8761/eureka/
